- pmp-ui/src/app/shared/dialog/dialog.component.ts
https://mosip.atlassian.net/browse/MOSIP-19278
> language code not sent after policy group mapping is fixed

- pmp-ui/src/app/core/services/logout.service.ts
> fixing the logout issue with the latest service based changes

- pmp-ui/src/app/shared/dialog/dialog.component.html
https://mosip.atlassian.net/browse/MOSIP-22043
> Added the success message and error message icon for left out languages

- .github/workflows/push_trigger.yml
> Made changes to node version.

- pmp-ui/src/app/features/resources/cert-upload/cert-upload.component.html
- pmp-ui/src/app/features/resources/cert-upload/cert-upload.component.scss
- pmp-ui/src/app/features/resources/cert-upload/cert-upload.component.ts
- pmp-ui/src/assets/config.json
https://mosip.atlassian.net/browse/MOSIP-28103
> upload file component change to check QA header less testing

- pmp-ui/src/app/features/resources/shared/mater-data-common-body/mater-data-common-body.component.html
- pmp-ui/src/app/features/resources/shared/mater-data-common-body/mater-data-common-body.component.scss
- pmp-ui/src/app/features/resources/shared/mater-data-common-body/mater-data-common-body.component.ts
This reverts commit 035e48639ba20bd32007758816ace396dcb6dc10.
> Revert "MOSIP-26354 : PMP UI: All active policies should be display in Policy group dropdown"

- pmp-reactjs-ui/nginx/nginx.conf
Reverts mosip/partner-management-portal#322
> Revert "updated nginx"

- pmp-reactjs-ui/src/pages/common/fields/DropdownComponent.js
- pmp-reactjs-ui/src/pages/policies/PoliciesFilter.js
Reverts mosip/partner-management-portal#377
> Revert "MOSIP-32957: Filter dropdown fixes"

- pmp-reactjs-ui/src/pages/dashboard/SelectPolicyPopup.js
[In Arabic](https://github.com/mosip/partner-management-portal/assets/106086523/081090c9-2bb8-4285-93a6-3f3a90e30477)
[In French](https://github.com/mosip/partner-management-portal/assets/106086523/c18b9e33-e2a9-4086-a550-69b04f951c58)
> MOSIP-33839: added missing translation for View More

- pmp-reactjs-ui/src/nav/HeaderNav.js
- pmp-reactjs-ui/src/pages/authenticationServices/CreateOidcClient.js
- pmp-reactjs-ui/src/pages/authenticationServices/OidcClientsList.js
- pmp-reactjs-ui/src/pages/authenticationServices/ViewOidcClientDetails.js
- pmp-reactjs-ui/src/pages/common/fields/DropdownComponent.js
- pmp-reactjs-ui/src/pages/common/fields/DropdownWithSearchComponent.js
- pmp-reactjs-ui/src/pages/policies/Policies.js
- pmp-reactjs-ui/src/pages/policies/RequestPolicy.js
[Screenshot (194)](https://github.com/mosip/partner-management-portal/assets/106086523/6330a335-14f6-4c68-8796-6db939cc97d5)
[Screenshot (195)](https://github.com/mosip/partner-management-portal/assets/106086523/7966947e-870f-4d4f-bcd8-901b10cb8047)
[Screenshot (196)](https://github.com/mosip/partner-management-portal/assets/106086523/9c15deca-ebbb-4b54-9d06-e46b7abd4fb8)
[Screenshot (197)](https://github.com/mosip/partner-management-portal/assets/106086523/509deebb-0f0f-4d7c-b0aa-a37e29f57855)
[Screenshot (198)](https://github.com/mosip/partner-management-portal/assets/106086523/9de7a753-ba7d-481c-962b-eea46ec39190)
[Screenshot (199)](https://github.com/mosip/partner-management-portal/assets/106086523/d184a87b-d9f7-4e43-a83c-0e9c46e3569e)
> MOSIP-33808: Alignment Issues in Policy screen on multi-language selection

- pmp-reactjs-ui/src/pages/authenticationServices/CreateOidcClient.js
- pmp-reactjs-ui/src/pages/authenticationServices/EditOidcClient.js
- pmp-reactjs-ui/src/pages/authenticationServices/GenerateApiKey.js
- pmp-reactjs-ui/src/pages/common/fields/DropdownComponent.js
- pmp-reactjs-ui/src/pages/common/fields/DropdownWithSearchComponent.js
- pmp-reactjs-ui/src/pages/policies/RequestPolicy.js
Reverts mosip/partner-management-portal#614
> Revert "MOSIP-34535: Modified the overlapping of dropdown options in some screens."

- pmp-reactjs-ui/src/pages/authenticationServices/ApiKeysList.js
- pmp-reactjs-ui/src/pages/authenticationServices/OidcClientsList.js
> MOSIP-34168: Resolved the alignment issue in tabels when logged in French/Arabic language

- pmp-reactjs-ui/src/pages/authenticationServices/ApiKeysList.js
- pmp-reactjs-ui/src/pages/authenticationServices/CreateOidcClient.js
- pmp-reactjs-ui/src/pages/authenticationServices/EditOidcClient.js
- pmp-reactjs-ui/src/pages/authenticationServices/GenerateApiKey.js
- pmp-reactjs-ui/src/pages/authenticationServices/OidcClientsList.js
- pmp-reactjs-ui/src/pages/certificates/PartnerCertificatesList.js
- pmp-reactjs-ui/src/pages/certificates/UploadCertificate.js
- pmp-reactjs-ui/src/pages/common/DeactivatePopup.js
- pmp-reactjs-ui/src/pages/common/ErrorMessage.js
- pmp-reactjs-ui/src/pages/common/SuccessMessage.js
- pmp-reactjs-ui/src/pages/dashboard/ConsentPopup.js
- pmp-reactjs-ui/src/pages/dashboard/Dashboard.js
- pmp-reactjs-ui/src/pages/dashboard/SelectPolicyPopup.js
- pmp-reactjs-ui/src/pages/deviceProviderServices/AddDevices.js
- pmp-reactjs-ui/src/pages/deviceProviderServices/AddSbi.js
- pmp-reactjs-ui/src/pages/deviceProviderServices/DevicesList.js
- pmp-reactjs-ui/src/pages/deviceProviderServices/SbiList.js
- pmp-reactjs-ui/src/pages/ftmProviderServices/AddFtm.js
- pmp-reactjs-ui/src/pages/ftmProviderServices/FtmList.js
- pmp-reactjs-ui/src/pages/ftmProviderServices/ViewFtmChipDetails.js
- pmp-reactjs-ui/src/pages/policies/PoliciesList.js
- pmp-reactjs-ui/src/pages/policies/RequestPolicy.js
@mayuradesh, I created reusable code for Error & Success messages all over the pages.
> MOSIP-35026: Code Refactor of Error & Success Messages.

- pmptest/pom.xml
Parent project of MOSIP Partner Management Portal - UI Tests
> updated pom

- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/fw/util/AdminTestUtil.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/kernel/util/ConfigManager.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/ApiKeyPage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/BasePage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/DashboardPage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/OidcClientPage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/PartnerCertificatePage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/PoliciesPage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/pages/RegisterPage.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/testcase/CreateApiKey.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/testcase/CreateOidecClient.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/testcase/NewUserPolicy.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/testcase/RegisterNewUser.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/utility/BaseClass.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/utility/GlobalConstants.java
- uitest-pmprevamp/src/main/java/io/mosip/testrig/pmprevampui/utility/TestRunner.java
- uitest-pmprevamp/src/main/resources/testngFile/testng.xml
MOSIP-33299 added testcases for revamp ui automation
> MOSIP-33299 added testcases for revamp ui automation

- .github/workflows/push-trigger.yml
MOSIP-36006 reverted the changes
>  MOSIP-36006 reverted the changes

- uitest-pmp/src/main/java/io/mosip/testrig/pmpui/kernel/util/ConfigManager.java
> MOSIP-36006 db query fix

- pmp-reactjs-ui/public/i18n/ara.json
- pmp-reactjs-ui/public/i18n/eng.json
- pmp-reactjs-ui/public/i18n/fra.json
- pmp-reactjs-ui/src/AppRoutes.js
- pmp-reactjs-ui/src/pages/admin/partners/PartnersList.js
- pmp-reactjs-ui/src/pages/admin/partners/ViewPartnerDetails.js
- pmp-reactjs-ui/src/pages/partner/ftmProviderServices/ViewFtmChipDetails.js
[![View partner Details page](https://github.com/user-attachments/assets/f5cadc67-30ac-4176-bfaa-2e84cdfda04f)]
> MOSIP-36320, MOSIP-36330: UI Development of View Partner Details & Download Certificate Button in same page.

- pmp-reactjs-ui/public/i18n/ara.json
- pmp-reactjs-ui/public/i18n/eng.json
- pmp-reactjs-ui/public/i18n/fra.json
- pmp-reactjs-ui/src/pages/admin/partners/PartnersList.js
- pmp-reactjs-ui/src/pages/admin/partners/ViewPartnerDetails.js
- pmp-reactjs-ui/src/pages/common/DeactivatePopup.js
- pmp-reactjs-ui/src/pages/partner/authenticationServices/OidcClientsList.js
[Screenshot](https://github.com/user-attachments/assets/01d2c2f9-9352-489c-9288-78e49cefead0)
> MOSIP-36341: UI Development Deactivate the Partner.

- pmp-reactjs-ui/src/pages/common/fields/TextInputComponent.js
> MOSIP-36490 : Enhanced the clearing text cross-icon in Input tab of Filter part.

- pmp-reactjs-ui/src/pages/admin/policyManager/ViewPolicy.js
- pmp-reactjs-ui/src/pages/admin/policyManager/ViewPolicyPopup.js
[Screenshot 2024-11-05 183147](https://github.com/user-attachments/assets/f4af5573-afb9-4a24-83a2-326eb6861b5b)
> MOSIP-36981, MOSIP-36991: Implemented Policy JSON pretty preview in Auth & Data Share View Page.

- .github/workflows/push-trigger.yml
[DSD-6882]Updated pushtrigger to suppport sonar-ui
> [DSD-6682]Update push-trigger.yml

- pmp-reactjs-ui/src/pages/admin/authenticationServices/AdminApiKeysList.js
- pmp-reactjs-ui/src/pages/partner/authenticationServices/ApiKeysList.js
> MOSIP-37966: Added api key unique check

- pmp-revamp-ui/src/pages/admin/authenticationServices/ViewAdminApiKeyDetails.js
- pmp-revamp-ui/src/pages/admin/authenticationServices/ViewAdminOidcClientDetails.js
- pmp-revamp-ui/src/pages/admin/certificates/ViewCertificateDetails.js
- pmp-revamp-ui/src/pages/admin/deviceProviderServices/ViewAdminDeviceDetails.js
- pmp-revamp-ui/src/pages/admin/deviceProviderServices/ViewAdminSbiDetails.js
- pmp-revamp-ui/src/pages/admin/ftmProviderServices/ViewAdminFtmChipDetails.js
- pmp-revamp-ui/src/pages/admin/partners/ViewPartnerDetails.js
- pmp-revamp-ui/src/pages/admin/policyManager/DeactivatePolicyPopup.js
- pmp-revamp-ui/src/pages/admin/policyManager/ViewPolicy.js
- pmp-revamp-ui/src/pages/admin/policyManager/ViewPolicyGroupDetails.js
- pmp-revamp-ui/src/pages/admin/policyRequests/ViewPolicyRequestDetails.js
**MOSIP-37491**
[Screenshot 2024-12-13 173745](https://github.com/user-attachments/assets/946fdf57-6cb2-4d38-8134-646a81455783)
**MOSIP-38260 :**
[Screenshot 2024-12-13 174730](https://github.com/user-attachments/assets/4574df57-e7ba-41e1-a795-f3d81fd1545b)
[Screenshot 2024-12-13 174758](https://github.com/user-attachments/assets/8649cd87-cb01-4b08-b93a-1457318be29d)
[Screenshot 2024-12-13 174834](https://github.com/user-attachments/assets/6d283f35-ce22-4ce2-972f-d67a6a9bbcba)
> MOSIP-37491, MOSIP-38260 : Resolved the Bugs

- uitest-pmp/pom.xml
> MOSIP-40469 Update pom.xml

- pmp-revamp-ui/src/pages/dashboard/Dashboard.js
> MOSIP-40089 : Partner Certificate Notification: Dashboard badge (Partner)

- uitest-pmp/pom.xml
Changed POM version to 1.2.2.1-SNAPSHOT for release
> Changed POM version to 1.2.2.1-SNAPSHOT for release
